# Generated by Django 5.0.3 on 2024-04-17 02:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now)),
                ('fecha_fin', models.DateField(default=datetime.datetime.now)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='reserves.estado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='reserves.profesor')),
                ('suplente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='reserves.suplente')),
            ],
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
