# Generated by Django 5.0.3 on 2024-04-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0002_clase_delete_tarjeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='titulo',
            new_name='nivel',
        ),
    ]
